import type { ERDSchema, SQLDialect, Table, Column, Relationship } from '@/types/schema';

export function generateDDL(schema: ERDSchema, dialect: SQLDialect): string {
  const tables = Object.values(schema.tables);
  const relationships = Object.values(schema.relationships);

  if (tables.length === 0) {
    return `-- No tables defined yet`;
  }

  const sorted = topologicalSort(tables, relationships);

  const statements: string[] = [];

  for (const table of sorted) {
    statements.push(generateCreateTable(table, dialect));
  }

  for (const rel of relationships) {
    const fk = generateForeignKey(rel, schema.tables, dialect);
    if (fk) statements.push(fk);
  }

  const header =
    dialect === 'mysql'
      ? `-- Generated by ERD Studio for MySQL\n-- Date: ${new Date().toISOString()}`
      : `-- Generated by ERD Studio for PostgreSQL\n-- Date: ${new Date().toISOString()}`;

  return header + '\n\n' + statements.join('\n\n');
}

function topologicalSort(tables: Table[], relationships: Relationship[]): Table[] {
  const tableMap = new Map(tables.map((t) => [t.id, t]));
  const inDegree = new Map<string, number>();
  const adjacency = new Map<string, string[]>();

  for (const t of tables) {
    inDegree.set(t.id, 0);
    adjacency.set(t.id, []);
  }

  for (const rel of relationships) {
    if (tableMap.has(rel.sourceTableId) && tableMap.has(rel.targetTableId)) {
      // source table must exist before target (target has FK referencing source)
      adjacency.get(rel.sourceTableId)!.push(rel.targetTableId);
      inDegree.set(rel.targetTableId, (inDegree.get(rel.targetTableId) ?? 0) + 1);
    }
  }

  const queue: string[] = [];
  for (const [id, deg] of inDegree) {
    if (deg === 0) queue.push(id);
  }

  const result: Table[] = [];
  while (queue.length > 0) {
    const current = queue.shift()!;
    const table = tableMap.get(current);
    if (table) result.push(table);

    for (const neighbor of adjacency.get(current) ?? []) {
      const newDeg = (inDegree.get(neighbor) ?? 1) - 1;
      inDegree.set(neighbor, newDeg);
      if (newDeg === 0) queue.push(neighbor);
    }
  }

  // If there are cycles, append remaining tables
  for (const t of tables) {
    if (!result.find((r) => r.id === t.id)) {
      result.push(t);
    }
  }

  return result;
}

function generateCreateTable(table: Table, dialect: SQLDialect): string {
  const q = dialect === 'mysql' ? '`' : '"';
  const lines: string[] = [];

  for (const col of table.columns) {
    lines.push('  ' + generateColumnDef(col, dialect));
  }

  // Primary key constraint
  const pkCols = table.columns.filter((c) => c.isPrimaryKey);
  if (pkCols.length > 0) {
    lines.push(`  PRIMARY KEY (${pkCols.map((c) => `${q}${c.name}${q}`).join(', ')})`);
  }

  // Unique constraints (non-PK)
  for (const col of table.columns) {
    if (col.isUnique && !col.isPrimaryKey) {
      lines.push(`  UNIQUE (${q}${col.name}${q})`);
    }
  }

  // Indexes
  for (const idx of table.indexes) {
    const colNames = idx.columnIds
      .map((cid) => table.columns.find((c) => c.id === cid)?.name)
      .filter(Boolean)
      .map((n) => `${q}${n}${q}`);
    if (colNames.length > 0) {
      const uniqueKw = idx.unique ? 'UNIQUE ' : '';
      lines.push(`  ${uniqueKw}INDEX ${q}${idx.name}${q} (${colNames.join(', ')})`);
    }
  }

  let ddl = `CREATE TABLE ${q}${table.name}${q} (\n${lines.join(',\n')}\n)`;

  if (dialect === 'mysql') {
    const engine = table.engine ?? 'InnoDB';
    const charset = table.charset ?? 'utf8mb4';
    ddl += ` ENGINE=${engine} DEFAULT CHARSET=${charset}`;
  }

  ddl += ';';

  if (table.comment) {
    ddl += ` -- ${table.comment}`;
  }

  return ddl;
}

function generateColumnDef(col: Column, dialect: SQLDialect): string {
  const q = dialect === 'mysql' ? '`' : '"';
  const parts: string[] = [`${q}${col.name}${q}`];

  parts.push(resolveDataType(col, dialect));

  if (!col.nullable) {
    parts.push('NOT NULL');
  }

  if (col.autoIncrement) {
    if (dialect === 'mysql') {
      parts.push('AUTO_INCREMENT');
    }
    // PostgreSQL auto-increment is handled in resolveDataType (SERIAL/BIGSERIAL)
  }

  if (col.defaultValue !== undefined && col.defaultValue !== '') {
    parts.push(`DEFAULT ${col.defaultValue}`);
  }

  return parts.join(' ');
}

function resolveDataType(col: Column, dialect: SQLDialect): string {
  const dt = col.dataType.toUpperCase();

  if (dialect === 'postgresql' && col.autoIncrement) {
    if (dt === 'INT' || dt === 'INTEGER') return 'SERIAL';
    if (dt === 'BIGINT') return 'BIGSERIAL';
    if (dt === 'SMALLINT') return 'SMALLSERIAL';
  }

  // Handle length/precision
  if (col.length && ['VARCHAR', 'CHAR', 'VARBINARY', 'BINARY'].includes(dt)) {
    return `${dt}(${col.length})`;
  }

  if (col.precision !== undefined && col.scale !== undefined && ['DECIMAL', 'NUMERIC'].includes(dt)) {
    return `${dt}(${col.precision}, ${col.scale})`;
  }

  if (col.enumValues && col.enumValues.length > 0 && (dt === 'ENUM' || dt === 'SET')) {
    const vals = col.enumValues.map((v) => `'${v}'`).join(', ');
    if (dialect === 'mysql') {
      return `${dt}(${vals})`;
    }
    // PostgreSQL doesn't have native ENUM inline, use VARCHAR
    return 'VARCHAR(255)';
  }

  return dt;
}

function generateForeignKey(
  rel: Relationship,
  tables: Record<string, Table>,
  dialect: SQLDialect,
): string | null {
  const sourceTable = tables[rel.sourceTableId];
  const targetTable = tables[rel.targetTableId];
  if (!sourceTable || !targetTable) return null;

  const q = dialect === 'mysql' ? '`' : '"';

  const sourceColNames = rel.sourceColumnIds
    .map((cid) => sourceTable.columns.find((c) => c.id === cid)?.name)
    .filter(Boolean);

  const targetColNames = rel.targetColumnIds
    .map((cid) => targetTable.columns.find((c) => c.id === cid)?.name)
    .filter(Boolean);

  if (sourceColNames.length === 0 || targetColNames.length === 0) return null;

  const fkName = rel.name ?? `fk_${targetTable.name}_${sourceTable.name}`;

  return (
    `ALTER TABLE ${q}${targetTable.name}${q}\n` +
    `  ADD CONSTRAINT ${q}${fkName}${q}\n` +
    `  FOREIGN KEY (${targetColNames.map((n) => `${q}${n}${q}`).join(', ')})\n` +
    `  REFERENCES ${q}${sourceTable.name}${q} (${sourceColNames.map((n) => `${q}${n}${q}`).join(', ')})\n` +
    `  ON DELETE ${rel.onDelete}\n` +
    `  ON UPDATE ${rel.onUpdate};`
  );
}
